DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pick;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  password TEXT NOT NULL
);

CREATE TABLE pick (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL, 
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  player TEXT NOT NULL,
  click BIT DEFAULT NULL
);
